# -*- coding: utf-8 -*-
"""Revisi Kuis 2 Mesin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11tW0GXRtLK-c4NuK0JDewQhfuQhX8i4P

**Import Libraries**
"""

import os
import random
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm import tqdm


import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix, roc_curve
)

"""**Ekstrak Data**"""

from google.colab import drive
drive.mount('/content/drive')

zip_path = '/content/drive/MyDrive/Mesin/HYGD.zip'
extract_path = '/content/drive/MyDrive/Mesin/HYGD'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

BASE_PATH = '/content/drive/MyDrive/Mesin/HYGD/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0'
IMAGES_DIR = os.path.join(BASE_PATH, 'Images')
OUTPUT_DIR = '/content/drive/MyDrive/Mesin/HYGD'

#Baca CSV
labels = pd.read_csv(
    '/content/drive/MyDrive/Mesin/HYGD/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0/Labels.csv'
)

#Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

"""# Exploratory Data Analysis (EDA)

**Informasi Dataset**
"""

print("Labels Data:")
print(labels.head())
print(f"Shape: {labels.shape}")
print(f"Columns: {labels.columns.tolist()}")

#Standardize kolom
labels.columns = labels.columns.str.strip()
labels = labels.rename(columns={
    "Image Name":    "image_name",
    "Patient":       "patient_id",
    "Label":         "label",
    "Quality Score": "quality_score"
})

#Binary label: GON+ = 1, GON- = 0
labels["label_bin"] = labels["label"].apply(
    lambda x: 1 if str(x).strip().upper() in ["GON+", "1", "POSITIVE"] else 0
)

labels["image_path"] = labels["image_name"].apply(
    lambda x: os.path.join(IMAGES_DIR, x)
)

#Filter gambar
labels["file_exists"] = labels["image_path"].apply(os.path.exists)
missing = labels[~labels["file_exists"]]
if len(missing) > 0:
    print(f"\n⚠️  {len(missing)} gambar tidak ditemukan, akan dilewati.")
labels = labels[labels["file_exists"]].reset_index(drop=True)

print(f"Total gambar valid: {len(labels)}")
print(f"\nUnique pasien: {labels['patient_id'].nunique()}")
print(f"\nDistribusi label:\n{labels['label_bin'].value_counts()}")
print(f"\nDistribusi Quality Score:\n{labels['quality_score'].describe()}")

#Grafik
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

#Class distribution
axes[0].bar(["GON- (0)", "GON+ (1)"],
            labels["label_bin"].value_counts().sort_index().values,
            color=["steelblue", "tomato"])
axes[0].set_title("Class Distribution")
axes[0].set_ylabel("Count")
for i, v in enumerate(labels["label_bin"].value_counts().sort_index().values):
    axes[0].text(i, v + 3, str(v), ha="center", fontweight="bold")

#Quality score distribution
axes[1].hist(labels["quality_score"], bins=10, color="mediumseagreen", edgecolor="black")
axes[1].set_title("Quality Score Distribution")
axes[1].set_xlabel("Quality Score (1–10)")
axes[1].set_ylabel("Count")

#Quality score by label
labels.boxplot(column="quality_score", by="label_bin", ax=axes[2],
               notch=False, patch_artist=True)
axes[2].set_title("Quality Score by Label")
axes[2].set_xlabel("Label (0=GON-, 1=GON+)")
axes[2].set_ylabel("Quality Score")
plt.suptitle("")

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "eda_overview.png"), dpi=150, bbox_inches="tight")
plt.show()

#Contoh gambar low / medium / high quality
def show_sample_images(df, title="Sample Images", save_path=None):
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))
    tier_labels = ["Low Quality (≤3)", "Medium Quality (4–6)", "High Quality (≥7)"]
    masks = [
        df["quality_score"] <= 3,
        (df["quality_score"] >= 4) & (df["quality_score"] <= 6),
        df["quality_score"] >= 7
    ]
    for ax, mask, lbl in zip(axes, masks, tier_labels):
        subset = df[mask]
        if len(subset) == 0:
            ax.set_title(f"{lbl}\n(No images)")
            ax.axis("off")
            continue
        row = subset.sample(1, random_state=SEED).iloc[0]
        img = Image.open(row["image_path"]).convert("RGB")
        ax.imshow(img)
        ax.set_title(f"{lbl}\nQ={row['quality_score']} | {row['label']}")
        ax.axis("off")
    plt.suptitle(title)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()

show_sample_images(labels, save_path=os.path.join(OUTPUT_DIR, "eda_samples.png"))

"""# Preprocessing Data

**Split Data**
"""

#Patient-Level Train/Val/Test Split (70 / 15 / 15)
patients = labels["patient_id"].values
y_all    = labels["label_bin"].values

gss_traintest = GroupShuffleSplit(n_splits=1, test_size=0.30, random_state=SEED)
train_idx, temp_idx = next(gss_traintest.split(labels, y_all, groups=patients))

labels_train = labels.iloc[train_idx].reset_index(drop=True)
labels_temp  = labels.iloc[temp_idx].reset_index(drop=True)

#Split temp → val & test (50/50 dari 30% = 15% : 15%)
gss_valtest = GroupShuffleSplit(n_splits=1, test_size=0.50, random_state=SEED)
val_idx, test_idx = next(gss_valtest.split(
    labels_temp,
    labels_temp["label_bin"].values,
    groups=labels_temp["patient_id"].values
))

labels_val  = labels_temp.iloc[val_idx].reset_index(drop=True)
labels_test = labels_temp.iloc[test_idx].reset_index(drop=True)

print("Patient-Level Split (70/15/15)")
print(f"Train : {len(labels_train):3d} images | {labels_train['patient_id'].nunique():3d} patients | GON+: {labels_train['label_bin'].sum()}")
print(f"Val   : {len(labels_val):3d} images | {labels_val['patient_id'].nunique():3d} patients | GON+: {labels_val['label_bin'].sum()}")
print(f"Test  : {len(labels_test):3d} images | {labels_test['patient_id'].nunique():3d} patients | GON+: {labels_test['label_bin'].sum()}")

#Verifikasi tidak ada pasien bocor
assert len(set(labels_train["patient_id"]) & set(labels_val["patient_id"]))  == 0, "LEAKAGE train-val!"
assert len(set(labels_train["patient_id"]) & set(labels_test["patient_id"])) == 0, "LEAKAGE train-test!"
assert len(set(labels_val["patient_id"])   & set(labels_test["patient_id"])) == 0, "LEAKAGE val-test!"

"""**Penanganan Class Imbalance**"""

#Resize
IMG_SIZE = 224

#Augmentasi untuk training
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

#Tanpa augmentasi untuk val/test
val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])


class GlaucomaDataset(Dataset):
    """Dataset class untuk HYGD — pakai variabel 'labels' (DataFrame)."""

    def __init__(self, dataframe, transform=None, use_quality=False):
        self.df          = dataframe.reset_index(drop=True)
        self.transform   = transform
        self.use_quality = use_quality

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(row["image_path"]).convert("RGB")
        if self.transform:
            img = self.transform(img)
        label = torch.tensor(row["label_bin"], dtype=torch.long)
        if self.use_quality:
            quality = torch.tensor(row["quality_score"] / 10.0, dtype=torch.float32)
            return img, label, quality
        return img, label

#Class Imbalance - Weighted Loss
n_neg = (labels_train["label_bin"] == 0).sum()
n_pos = (labels_train["label_bin"] == 1).sum()
weight_neg = (n_neg + n_pos) / (2.0 * n_neg)
weight_pos = (n_neg + n_pos) / (2.0 * n_pos)
class_weights = torch.tensor([weight_neg, weight_pos], dtype=torch.float32).to(DEVICE)
print(f"Class weights → GON-: {weight_neg:.3f} | GON+: {weight_pos:.3f}")

"""# CNN Construction & Quality Aware CNN

**Custom CNN Architecture**
"""

class CustomCNN(nn.Module):

    def __init__(self, num_classes=2):
        super(CustomCNN, self).__init__()

        self.features = nn.Sequential(
            # Block 1: 3 → 32  (224 → 112)
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            # Block 2: 32 → 64  (112 → 56)
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            # Block 3: 64 → 128  (56 → 28)
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            # Block 4: 128 → 256  (28 → 14)
            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
        )

        self.gap = nn.AdaptiveAvgPool2d(1)

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 128),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(128, num_classes),
        )

    def forward(self, x):
        x = self.features(x)
        x = self.gap(x)
        x = self.classifier(x)
        return x

"""**Quality-Aware CNN**"""

class QualityAwareCNN(nn.Module):

    def __init__(self, num_classes=2):
        super(QualityAwareCNN, self).__init__()

        self.features = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
        )

        self.gap = nn.AdaptiveAvgPool2d(1)

        #+1 karena quality score di-concat ke feature vector
        self.classifier = nn.Sequential(
            nn.Linear(256 + 1, 128),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(128, num_classes),
        )

    def forward(self, x, quality):
        x = self.features(x)
        x = self.gap(x)
        x = x.view(x.size(0), -1)
        q = quality.unsqueeze(1)
        x = torch.cat([x, q], dim=1)
        x = self.classifier(x)
        return x

"""**Training & Evaluation Functions**"""

def train_one_epoch(model, loader, optimizer, criterion, device, use_quality=False):
    model.train()
    total_loss, correct, total = 0, 0, 0
    for batch in tqdm(loader, desc="  Training", leave=False):
        if use_quality:
            imgs, lbl, quality = batch
            quality = quality.to(device)
        else:
            imgs, lbl = batch
        imgs, lbl = imgs.to(device), lbl.to(device)

        optimizer.zero_grad()
        outputs = model(imgs, quality) if use_quality else model(imgs)
        loss = criterion(outputs, lbl)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * imgs.size(0)
        correct    += (outputs.argmax(1) == lbl).sum().item()
        total      += imgs.size(0)

    return total_loss / total, correct / total


def evaluate(model, loader, criterion, device, use_quality=False):
    model.eval()
    total_loss, correct, total = 0, 0, 0
    all_preds, all_probs, all_labels = [], [], []

    with torch.no_grad():
        for batch in loader:
            if use_quality:
                imgs, lbl, quality = batch
                quality = quality.to(device)
            else:
                imgs, lbl = batch
            imgs, lbl = imgs.to(device), lbl.to(device)

            outputs = model(imgs, quality) if use_quality else model(imgs)
            loss    = criterion(outputs, lbl)

            probs = torch.softmax(outputs, dim=1)[:, 1]
            preds = outputs.argmax(1)

            total_loss += loss.item() * imgs.size(0)
            correct    += (preds == lbl).sum().item()
            total      += imgs.size(0)

            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(lbl.cpu().numpy())

    return (total_loss / total, correct / total,
            np.array(all_labels), np.array(all_preds), np.array(all_probs))


def compute_metrics(y_true, y_pred, y_prob):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return {
        "Accuracy"    : accuracy_score(y_true, y_pred),
        "Precision"   : precision_score(y_true, y_pred, zero_division=0),
        "Recall/Sens" : recall_score(y_true, y_pred, zero_division=0),
        "Specificity" : tn / (tn + fp) if (tn + fp) > 0 else 0,
        "F1-Score"    : f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC"     : roc_auc_score(y_true, y_prob),
    }


def train_model(model, train_loader, val_loader, optimizer, criterion,
                scheduler, num_epochs, device, use_quality=False,
                save_path="best_model.pth", patience=10):
    best_val_loss    = float("inf")
    patience_counter = 0
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    for epoch in range(1, num_epochs + 1):
        tr_loss, tr_acc = train_one_epoch(
            model, train_loader, optimizer, criterion, device, use_quality)
        vl_loss, vl_acc, _, _, _ = evaluate(
            model, val_loader, criterion, device, use_quality)

        scheduler.step(vl_loss)
        history["train_loss"].append(tr_loss)
        history["val_loss"].append(vl_loss)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(vl_acc)

        print(f"Epoch [{epoch:3d}/{num_epochs}] "
              f"Train Loss: {tr_loss:.4f} Acc: {tr_acc:.4f} | "
              f"Val Loss: {vl_loss:.4f} Acc: {vl_acc:.4f}")

        if vl_loss < best_val_loss:
            best_val_loss    = vl_loss
            patience_counter = 0
            torch.save(model.state_dict(), save_path)
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"⏹ Early stopping di epoch {epoch}")
                break

    return history


def plot_training_history(history, title="Training History", save_path=None):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(history["train_loss"], label="Train Loss")
    ax1.plot(history["val_loss"],   label="Val Loss")
    ax1.set_title(f"{title} — Loss")
    ax1.set_xlabel("Epoch"); ax1.set_ylabel("Loss")
    ax1.legend()

    ax2.plot(history["train_acc"], label="Train Acc")
    ax2.plot(history["val_acc"],   label="Val Acc")
    ax2.set_title(f"{title} — Accuracy")
    ax2.set_xlabel("Epoch"); ax2.set_ylabel("Accuracy")
    ax2.legend()

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()

"""**Data Loaders**"""

BATCH_SIZE  = 32
NUM_WORKERS = 0

#Baseline (tanpa quality score)
train_dataset = GlaucomaDataset(labels_train, transform=train_transform, use_quality=False)
val_dataset   = GlaucomaDataset(labels_val,   transform=val_transform,   use_quality=False)
test_dataset  = GlaucomaDataset(labels_test,  transform=val_transform,   use_quality=False)

#Quality-Aware (dengan quality score)
train_dataset_qa = GlaucomaDataset(labels_train, transform=train_transform, use_quality=True)
val_dataset_qa   = GlaucomaDataset(labels_val,   transform=val_transform,   use_quality=True)
test_dataset_qa  = GlaucomaDataset(labels_test,  transform=val_transform,   use_quality=True)

train_loader    = DataLoader(train_dataset,    batch_size=BATCH_SIZE, shuffle=True,  num_workers=NUM_WORKERS)
val_loader      = DataLoader(val_dataset,      batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
test_loader     = DataLoader(test_dataset,     batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

train_loader_qa = DataLoader(train_dataset_qa, batch_size=BATCH_SIZE, shuffle=True,  num_workers=NUM_WORKERS)
val_loader_qa   = DataLoader(val_dataset_qa,   batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
test_loader_qa  = DataLoader(test_dataset_qa,  batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

"""**Train Baseline CNN**"""

print("\n" + "="*60)
print("  TRAINING BASELINE CNN")
print("="*60)

NUM_EPOCHS = 50
LR         = 1e-3

SAVE_BASELINE = os.path.join(OUTPUT_DIR, "baseline_best.pth")
SAVE_QA       = os.path.join(OUTPUT_DIR, "qa_best.pth")

baseline_model = CustomCNN(num_classes=2).to(DEVICE)
optimizer_b    = optim.Adam(baseline_model.parameters(), lr=LR, weight_decay=1e-4)
criterion_b    = nn.CrossEntropyLoss(weight=class_weights)
scheduler_b    = optim.lr_scheduler.ReduceLROnPlateau(optimizer_b, patience=5, factor=0.5)

history_b = train_model(
    baseline_model, train_loader, val_loader,
    optimizer_b, criterion_b, scheduler_b,
    NUM_EPOCHS, DEVICE,
    save_path=SAVE_BASELINE, patience=10
)

plot_training_history(history_b, "Baseline CNN",
                      os.path.join(OUTPUT_DIR, "baseline_history.png"))

"""**Train Quality-Aware CNN**"""

print("\n" + "="*60)
print("  TRAINING QUALITY-AWARE CNN")
print("="*60)

qa_model    = QualityAwareCNN(num_classes=2).to(DEVICE)
optimizer_q = optim.Adam(qa_model.parameters(), lr=LR, weight_decay=1e-4)
criterion_q = nn.CrossEntropyLoss(weight=class_weights)
scheduler_q = optim.lr_scheduler.ReduceLROnPlateau(optimizer_q, patience=5, factor=0.5)

history_q = train_model(
    qa_model, train_loader_qa, val_loader_qa,
    optimizer_q, criterion_q, scheduler_q,
    NUM_EPOCHS, DEVICE, use_quality=True,
    save_path=SAVE_QA, patience=10
)

plot_training_history(history_q, "Quality-Aware CNN",
                      os.path.join(OUTPUT_DIR, "qa_history.png"))

"""**Test Set Final Evaluation**"""

print("\n" + "="*60)
print("  TEST SET EVALUATION")
print("="*60)

#Load best weights
baseline_model.load_state_dict(torch.load(SAVE_BASELINE, map_location=DEVICE, weights_only=True))
qa_model.load_state_dict(torch.load(SAVE_QA, map_location=DEVICE, weights_only=True))

#Evaluasi
_, _, y_true_b, y_pred_b, y_prob_b = evaluate(baseline_model, test_loader,    criterion_b, DEVICE)
_, _, y_true_q, y_pred_q, y_prob_q = evaluate(qa_model,       test_loader_qa, criterion_q, DEVICE, use_quality=True)

metrics_b = compute_metrics(y_true_b, y_pred_b, y_prob_b)
metrics_q = compute_metrics(y_true_q, y_pred_q, y_prob_q)

#Print comparison table
print(f"\n{'Metric':<20} {'Baseline CNN':>15} {'Quality-Aware CNN':>18}")
print("-" * 55)
for key in metrics_b:
    print(f"{key:<20} {metrics_b[key]:>15.4f} {metrics_q[key]:>18.4f}")

"""# Evaluation

**Confusion Matrix & ROC Curve**
"""

fig, axes = plt.subplots(1, 4, figsize=(20, 5))

cm_b = confusion_matrix(y_true_b, y_pred_b)
sns.heatmap(cm_b, annot=True, fmt="d", cmap="Blues", ax=axes[0],
            xticklabels=["GON-", "GON+"], yticklabels=["GON-", "GON+"])
axes[0].set_title("Baseline CNN\nConfusion Matrix")
axes[0].set_ylabel("True"); axes[0].set_xlabel("Predicted")

cm_q = confusion_matrix(y_true_q, y_pred_q)
sns.heatmap(cm_q, annot=True, fmt="d", cmap="Oranges", ax=axes[1],
            xticklabels=["GON-", "GON+"], yticklabels=["GON-", "GON+"])
axes[1].set_title("Quality-Aware CNN\nConfusion Matrix")
axes[1].set_ylabel("True"); axes[1].set_xlabel("Predicted")

fpr_b, tpr_b, _ = roc_curve(y_true_b, y_prob_b)
axes[2].plot(fpr_b, tpr_b, label=f"Baseline (AUC={metrics_b['ROC-AUC']:.3f})")
axes[2].plot([0, 1], [0, 1], "k--")
axes[2].set_title("Baseline CNN\nROC Curve")
axes[2].set_xlabel("FPR"); axes[2].set_ylabel("TPR")
axes[2].legend()

fpr_q, tpr_q, _ = roc_curve(y_true_q, y_prob_q)
axes[3].plot(fpr_q, tpr_q, color="orange",
             label=f"QA-CNN (AUC={metrics_q['ROC-AUC']:.3f})")
axes[3].plot([0, 1], [0, 1], "k--")
axes[3].set_title("Quality-Aware CNN\nROC Curve")
axes[3].set_xlabel("FPR"); axes[3].set_ylabel("TPR")
axes[3].legend()

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "evaluation_results.png"), dpi=150, bbox_inches="tight")
plt.show()

"""**Error Analysis**"""

def show_error_cases(df_test_set, y_true, y_pred, y_prob, save_path=None):
    fp_idx = np.where((y_pred == 1) & (y_true == 0))[0]
    fn_idx = np.where((y_pred == 0) & (y_true == 1))[0]

    n_fp = min(3, len(fp_idx))
    n_fn = min(3, len(fn_idx))

    if n_fp == 0 and n_fn == 0:
        print("Tidak ada FP maupun FN untuk ditampilkan.")
        return

    n_cols = max(n_fp, n_fn, 1)
    fig, axes = plt.subplots(2, n_cols, figsize=(4 * n_cols, 8))
    if n_cols == 1:
        axes = axes.reshape(2, 1)

    #Baris atas: False Positives
    for col in range(n_cols):
        ax = axes[0, col]
        if col < n_fp:
            idx = fp_idx[col]
            row = df_test_set.iloc[idx]
            img = Image.open(row["image_path"]).convert("RGB")
            ax.imshow(img)
            ax.set_title(f"FALSE POSITIVE\nTrue: GON- | Pred: GON+\nConf: {y_prob[idx]:.2f} | Q={row['quality_score']}")
        else:
            ax.set_visible(False)
        ax.axis("off")

    #Baris bawah: False Negatives
    for col in range(n_cols):
        ax = axes[1, col]
        if col < n_fn:
            idx = fn_idx[col]
            row = df_test_set.iloc[idx]
            img = Image.open(row["image_path"]).convert("RGB")
            ax.imshow(img)
            ax.set_title(f"FALSE NEGATIVE\nTrue: GON+ | Pred: GON-\nConf: {1-y_prob[idx]:.2f} | Q={row['quality_score']}")
        else:
            ax.set_visible(False)
        ax.axis("off")

    plt.suptitle("Error Analysis — False Positives & False Negatives", fontsize=14)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()

show_error_cases(labels_test, y_true_b, y_pred_b, y_prob_b,
                 save_path=os.path.join(OUTPUT_DIR, "error_analysis_baseline.png"))

"""**Quality Stratified Evaluation**"""

def get_quality_tier_metrics(df_test_set, y_true, y_pred, y_prob):
    "Hitung metrics per tier kualitas untuk SATU model. Return dict {tier_name: metrics_dict_or_None}."
    df_eval = df_test_set.copy()
    df_eval["y_true"] = y_true
    df_eval["y_pred"] = y_pred
    df_eval["y_prob"] = y_prob

    tiers = {
        "Low (1–3)":    df_eval["quality_score"] <= 3,
        "Medium (4–6)": (df_eval["quality_score"] >= 4) & (df_eval["quality_score"] <= 6),
        "High (7–10)":  df_eval["quality_score"] >= 7,
    }

    results = {}
    for tier_name, mask in tiers.items():
        subset = df_eval[mask]
        if len(subset) < 2 or subset["y_true"].nunique() < 2:
            results[tier_name] = {"n": len(subset), "metrics": None}
            continue
        m = compute_metrics(subset["y_true"].values,
                            subset["y_pred"].values,
                            subset["y_prob"].values)
        results[tier_name] = {"n": len(subset), "metrics": m}
    return results


def evaluate_by_quality_both_models(df_test_set,
                                     y_true_baseline, y_pred_baseline, y_prob_baseline,
                                     y_true_qa, y_pred_qa, y_prob_qa):
    "Bandingkan Baseline CNN vs Quality-Aware CNN per tier kualitas, side-by-side."

    results_b = get_quality_tier_metrics(df_test_set, y_true_baseline, y_pred_baseline, y_prob_baseline)
    results_q = get_quality_tier_metrics(df_test_set, y_true_qa, y_pred_qa, y_prob_qa)

    metric_keys = ["Accuracy", "Precision", "Recall/Sens", "Specificity", "F1-Score", "ROC-AUC"]

    print("\n" + "="*78)
    print(" QUALITY-STRATIFIED EVALUATION — BASELINE vs QUALITY-AWARE CNN")
    print("="*78)

    for tier_name in results_b.keys():
        n_b = results_b[tier_name]["n"]
        n_q = results_q[tier_name]["n"]
        m_b = results_b[tier_name]["metrics"]
        m_q = results_q[tier_name]["metrics"]

        print(f"\n {tier_name} (n_baseline={n_b}, n_qa={n_q})")
        if m_b is None and m_q is None:
            print("  Tidak cukup data untuk kedua model.")
            continue

        print(f"  {'Metric':<15} {'Baseline CNN':>15} {'Quality-Aware CNN':>20}")
        print("  " + "-" * 52)
        for key in metric_keys:
            v_b = f"{m_b[key]:.4f}" if m_b is not None else "N/A"
            v_q = f"{m_q[key]:.4f}" if m_q is not None else "N/A"
            print(f"  {key:<15} {v_b:>15} {v_q:>20}")

    return results_b, results_q


quality_tier_results_baseline, quality_tier_results_qa = evaluate_by_quality_both_models(
    labels_test,
    y_true_b, y_pred_b, y_prob_b,
    y_true_q, y_pred_q, y_prob_q
)